
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: flask_production_recipes
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://root:root@cluster0.cxbss.mongodb.net/learn
      - SECRET_KEY=76574c8da972c8649d44c335467a2d90
      - JWT_SECRET_KEY=76574c8da972c8649d44c335467a2d90
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  mongo_data:
